image: tmcglinn/ada_gitpod

vscode:
  extensions:
    - adacore.ada@22.0.5:b56gZDvQ5KBm6u34IBzm1g==

tasks:
  - before: alr toolchain --select gnat_native && alr toolchain --select gprbuild && eval $(alr printenv)
