name = "adabots_examples"
description = "Replace this name / description for your own project"
version = "1.1.0"

authors = ["Your Name"]
maintainers = ["Your Name <your@email.com>"]
maintainers-logins = ["YourGithubLogin"]

tags = ["adabots", "computercraft", "yourtag"]

[[depends-on]]  # This line was added by `alr with`
adabots = "^1.8.1"  # This line was added by `alr with`
