name = "adabots_examples"
description = "Replace this name / description for your own project"
version = "1.1.0"

authors = ["Your Name"]
maintainers = ["Your Name <your@email.com>"]
maintainers-logins = ["YourGithubLogin"]

tags = ["adabots", "computercraft", "yourtag"]

[[depends-on]]  # This line was added by `alr with`
adabots = "1.3.0"  # This line was added by `alr with`
aaa = "0.2.6"
aws = "23.0.0"
gnatcoll = "23.0.0"
gnat_native = "12.2.1"
gprbuild = "22.0.1"
libgpr = "23.0.0"
make = "4.3.0"
openssl = "3.0.2"
xmlada = "23.0.0"
