/* Configuration for adabots_examples generated by Alire */
#ifndef ADABOTS_EXAMPLES_CONFIG_H
#define ADABOTS_EXAMPLES_CONFIG_H

#define CRATE_VERSION "1.1.0"
#define CRATE_NAME "adabots_examples"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
